### ISSUE TITLE
Decide on naming convention of the new seasons

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#10]
TBD with @WorldCereal/valencia-team and @WorldCereal/unistra-team

**Comment by jdegerickx** [comment]
Internally we stick for now to 1 winter season and up to 2 summer seasons.
For each AEZ, these seasons should be merged to 2-3 seasons.
Resulting seasons should be named chronologically (season A, season B and season C), depending on timing of EOS?
Do we need to make sure that similar seasons get the same name across neighbouring AEZ?

**Comment by kvantricht** [comment]
@befranch for now we had no clear comment or suggestion from advisory board with regard to this.
How do you suggest to proceed? Can we settle soon on a naming convention both ESA and advisory board can agree with?

**Comment by kvantricht** [comment]
@befranch @MolettoLobos gentle reminder ...

**Comment by angui3** [comment]
After a productive discussion between VITO and UV team it has been reached an agreement to define two seasons: A and B.  The Season A will be based on the first End of Season of the year independently of which crop type it is. In the northern hemisphere it would be wheat, for example, as it is the one with the first EOS.
