### ISSUE TITLE
Allow to safely deploy custom models to a location where OpenEO can access them

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#109]
@jdries we need a solution in the short term for the public demo so we need a bilateral on this to discuss options.

**Comment by kvantricht** [comment]
@kvantricht to organize a meeting.

**Comment by kvantricht** [comment]
possible approaches to pursue:

### In-house Artifactory
- Current approach but requires an authentication key
- How to manage the key in public demo?
- Can we allow anonymous upload to specific bucket?
- How to manage auto-cleanup of artifacts in this repository
- Inform the users that this is just one way and that other users can "see" their models
@VincentVerelst to discuss with DevOps on what is possible here

### Hugging face model repository
- Either a user sets up their own account
- Or worldcereal project account, but then it looks a lot like the Artifactory approach, though with storage and bandwidth limitations
@kvantricht to pursue this option in more depth

Importantly, this option may not be a permanent one, as ultimately openEO will do the CatBoost training and immediately expose this model publicly.

**Comment by VincentVerelst** [comment]
Had a discussion with DevOps and anonymously deploying to a certain repo on Artifactory was a big no, even if we did an auto-cleanup of the repository. 

They suggested using a public S3 bucket.

**Comment by kvantricht** [comment]
@HansVRP to check for s3 options.

**Comment by kvantricht** [comment]
@pvbouwel is working on a solution using object storage and integration with OIDV in order for the openEO authentication to be reused for the s3 storage option.

**Comment by jdries** [comment]
closing: we have a solution in place, the openEO S3 proxy.
