### ISSUE TITLE
Track usage of WorldCereal job and their process graph custom parameters

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#110]
To be discussed with Pratichhya.

**Comment by VincentVerelst** [comment]
Grafana allows to set up SQL queries to get various job statistics: https://grafana.intern.vgt.vito.be/dashboards. However, probably not possible for custom process graph parameters.

**Comment by jdries** [comment]
Good use case for APEx.

**Comment by jdries** [comment]
When invoked via UDP, some tracking already happens, with the parameters available there, it is possible to find users and job parameters.



![Image](https://github.com/user-attachments/assets/e5d515d5-edc4-4363-9312-b304922db652)

**Comment by kvantricht** [comment]
To discuss further in light of the public demo. @kvantricht to organize a meeting for this.

**Comment by kvantricht** [comment]
When using the notebook and the `generate_map` functionality, we should **control things like job title and description** to be able to filter on WorldCereal jobs. Process graph, market place info (cost) is stored for quite some time. When jobs is found, process graph can be inspected to find user parameters. Dashboard can be created based on these filters.

These things should be set and controlled here: https://github.com/WorldCereal/worldcereal-classification/blob/main/src/worldcereal/job.py#L270:L279

Based on user ID of the job, it can be traced where in the world the job was submitted.

**Comment by kvantricht** [comment]
Check with openEO devs on what kind of pattern we have to hard code in title/description so filtering will be easiest.

**Comment by HansVRP** [comment]
To connect with Pratichhya

**Comment by VincentVerelst** [comment]
We currently have a pre-defined Kibana query that filters on jobs which have 'worldcereal', 'Worldcereal', or 'WorldCereal' in the title. By default the last 7 days are shown, but this can easily be adjusted. 

- [CDSE](https://kibana-1.prod.warsaw.marketplace.dataspace.copernicus.eu/app/kibana#/dashboard/2ac8fb30-2639-11ee-8091-1bebee325886?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'9c340150-158d-11ee-8091-1bebee325886',key:query,negate:!f,type:custom,value:'%7B%22bool%22:%7B%22minimum_should_match%22:1,%22should%22:%5B%7B%22wildcard%22:%7B%22jobName%22:%7B%22value%22:%22*worldcereal*%22%7D%7D%7D,%7B%22wildcard%22:%7B%22jobName%22:%7B%22value%22:%22*Worldcereal*%22%7D%7D%7D,%7B%22wildcard%22:%7B%22jobName%22:%7B%22value%22:%22*WorldCereal*%22%7D%7D%7D%5D%7D%7D'),query:(bool:(minimum_should_match:1,should:!((wildcard:(jobName:(value:'*worldcereal*'))),(wildcard:(jobName:(value:'*Worldcereal*'))),(wildcard:(jobName:(value:'*WorldCereal*')))))))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(),gridData:(h:15,i:'904e6d0f-7804-418b-b84b-c2ded9de6a33',w:24,x:0,y:0),id:d49d8f80-2239-11ee-8091-1bebee325886,panelIndex:'904e6d0f-7804-418b-b84b-c2ded9de6a33',type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:15,i:d494ff9e-5e86-42bb-9203-6af075304420,w:24,x:24,y:0),id:'69958170-2239-11ee-8091-1bebee325886',panelIndex:d494ff9e-5e86-42bb-9203-6af075304420,type:visualization,version:'7.5.1'),(embeddableConfig:(title:''),gridData:(h:5,i:'2ab79f63-f752-42d4-8f77-22f1fdf22afb',w:48,x:0,y:15),id:'717760b0-18de-11ef-8091-1bebee325886',panelIndex:'2ab79f63-f752-42d4-8f77-22f1fdf22afb',type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:16,i:c7522549-c9f4-4701-a078-60126802d94b,w:12,x:0,y:20),id:ab31cd40-82c5-11ee-8091-1bebee325886,panelIndex:c7522549-c9f4-4701-a078-60126802d94b,type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:16,i:cd6d7dd7-075f-4c34-9167-d9b9a1180f8d,w:12,x:12,y:20),id:dc502690-18cc-11ef-8091-1bebee325886,panelIndex:cd6d7dd7-075f-4c34-9167-d9b9a1180f8d,type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:16,i:d45661ff-a338-4319-8eb3-977fa8c3cb42,w:12,x:24,y:20),id:'4badfe70-7951-11ee-8091-1bebee325886',panelIndex:d45661ff-a338-4319-8eb3-977fa8c3cb42,type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:16,i:'3e955c19-8e4a-44d9-8dd6-396c87726922',w:12,x:36,y:20),id:'5e637d10-223a-11ee-8091-1bebee325886',panelIndex:'3e955c19-8e4a-44d9-8dd6-396c87726922',type:visualization,version:'7.5.1'),(embeddableConfig:(title:''),gridData:(h:5,i:'0a5baa08-7581-4be2-9721-8b8a4f683361',w:48,x:0,y:36),id:cf5f8f00-18dd-11ef-8091-1bebee325886,panelIndex:'0a5baa08-7581-4be2-9721-8b8a4f683361',type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:15,i:d99eecf9-faf7-4736-b09d-9cb5b9572b76,w:12,x:0,y:41),id:'1f74f430-223a-11ee-8091-1bebee325886',panelIndex:d99eecf9-faf7-4736-b09d-9cb5b9572b76,type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:15,i:'30384b79-ef09-4bed-af35-8ab0902adb31',w:12,x:12,y:41),id:'18d34c60-18db-11ef-8091-1bebee325886',panelIndex:'30384b79-ef09-4bed-af35-8ab0902adb31',type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:15,i:f46dd291-fb7c-47aa-aaf2-e286eb0bfbc1,w:24,x:24,y:56),id:'096d31b0-223b-11ee-8091-1bebee325886',panelIndex:f46dd291-fb7c-47aa-aaf2-e286eb0bfbc1,type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:15,i:d227b952-4a98-4fab-8743-aabd799d8085,w:24,x:0,y:56),id:c830e840-223a-11ee-8091-1bebee325886,panelIndex:d227b952-4a98-4fab-8743-aabd799d8085,type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:14,i:a299c07a-e710-429a-823d-75cb19d4696e,w:48,x:0,y:71),id:'2b60c0c0-223b-11ee-8091-1bebee325886',panelIndex:a299c07a-e710-429a-823d-75cb19d4696e,type:visualization,version:'7.5.1'),(embeddableConfig:(),gridData:(h:15,i:'6709f01a-51f3-4644-a9b7-e2722806ffe6',w:24,x:24,y:41),id:a5688cf0-18e3-11ef-8091-1bebee325886,panelIndex:'6709f01a-51f3-4644-a9b7-e2722806ffe6',type:visualization,version:'7.5.1')),query:(language:kuery,query:''),timeRestore:!f,title:'Marketplace%20-%20Costs',viewMode:view))
- [Terrascope](https://kibana-apps.vgt.vito.be/app/kibana#/dashboard/c141ce70-a75b-11eb-bc45-753cf0cde572?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now))&_a=(description:%27%27,filters:!((%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:ccab6f80-a758-11eb-bc45-753cf0cde572,key:query,negate:!f,type:custom,value:%27%7B%22bool%22:%7B%22minimum_should_match%22:1,%22should%22:%5B%7B%22wildcard%22:%7B%22jobName%22:%7B%22value%22:%22*worldcereal*%22%7D%7D%7D,%7B%22wildcard%22:%7B%22jobName%22:%7B%22value%22:%22*Worldcereal*%22%7D%7D%7D,%7B%22wildcard%22:%7B%22jobName%22:%7B%22value%22:%22*WorldCereal*%22%7D%7D%7D%5D%7D%7D%27),query:(bool:(minimum_should_match:1,should:!((wildcard:(jobName:(value:%27*worldcereal*%27))),(wildcard:(jobName:(value:%27*Worldcereal*%27))),(wildcard:(jobName:(value:%27*WorldCereal*%27)))))))),fullScreenMode:!f,options:(hidePanelTitles:!f,useMargins:!t),panels:!((embeddableConfig:(),gridData:(h:18,i:%273b585e89-a403-4351-b320-0c666c8f695b%27,w:16,x:0,y:0),id:a3e8af10-a75b-11eb-bc45-753cf0cde572,panelIndex:%273b585e89-a403-4351-b320-0c666c8f695b%27,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:18,i:d2309e96-90f2-46ab-99d1-44f5f67897b4,w:15,x:16,y:0),id:%2792b57ec0-1484-11ed-9c26-3f76720e6a27%27,panelIndex:d2309e96-90f2-46ab-99d1-44f5f67897b4,type:visualization,version:%277.5.1%27),(embeddableConfig:(title:%27Marketplace%20-%20Total%20credits%27,vis:(colors:(billed:%23508642,skipped:%23F2C96D))),gridData:(h:18,i:f72542a1-1627-486e-87f3-6bdb93ad6e1a,w:17,x:31,y:0),id:d724b8f0-a75c-11eb-bc45-753cf0cde572,panelIndex:f72542a1-1627-486e-87f3-6bdb93ad6e1a,title:%27Marketplace%20-%20Total%20credits%27,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:16,i:%2763dadab4-557a-4a02-b67a-e72abd530762%27,w:12,x:0,y:18),id:d2084660-c9ea-11eb-bc45-753cf0cde572,panelIndex:%2763dadab4-557a-4a02-b67a-e72abd530762%27,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:16,i:d066514b-182a-4f47-a817-0b0a22bd6946,w:16,x:12,y:18),id:d30ec610-a75d-11eb-bc45-753cf0cde572,panelIndex:d066514b-182a-4f47-a817-0b0a22bd6946,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:16,i:%279047a98b-59b6-405c-9566-edf02ed37679%27,w:20,x:28,y:18),id:%274c9030c0-a75c-11eb-bc45-753cf0cde572%27,panelIndex:%279047a98b-59b6-405c-9566-edf02ed37679%27,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:15,i:%2755408dd5-c495-41fb-9710-3ee9087abfe9%27,w:16,x:0,y:34),id:%2770bb6170-b6e0-11eb-bc45-753cf0cde572%27,panelIndex:%2755408dd5-c495-41fb-9710-3ee9087abfe9%27,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:15,i:ad7ca16c-9773-4418-9f33-dfc297554f46,w:15,x:16,y:34),id:%27783a0550-b6e0-11eb-bc45-753cf0cde572%27,panelIndex:ad7ca16c-9773-4418-9f33-dfc297554f46,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:15,i:%2761beff2e-fae0-43e0-9159-76df7675a1ea%27,w:17,x:31,y:34),id:%27744bf160-3025-11ec-9c26-3f76720e6a27%27,panelIndex:%2761beff2e-fae0-43e0-9159-76df7675a1ea%27,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:15,i:%277501324f-2034-4017-8d5e-1b0cc0b703ec%27,w:16,x:0,y:49),id:%275e2c4c30-1f8b-11ed-9c26-3f76720e6a27%27,panelIndex:%277501324f-2034-4017-8d5e-1b0cc0b703ec%27,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:15,i:aea4ba94-dbad-4c04-aac6-7506f0a5d93f,w:15,x:16,y:49),id:c5f30c20-c2d3-11eb-bc45-753cf0cde572,panelIndex:aea4ba94-dbad-4c04-aac6-7506f0a5d93f,type:visualization,version:%277.5.1%27),(embeddableConfig:(),gridData:(h:15,i:%271c2fe732-e901-4691-b5a2-67e9688c1a0f%27,w:17,x:31,y:49),id:%27841fbda0-a75a-11eb-bc45-753cf0cde572%27,panelIndex:%271c2fe732-e901-4691-b5a2-67e9688c1a0f%27,type:visualization,version:%277.5.1%27)),query:(language:kuery,query:%27%27),timeRestore:!f,title:%27Marketplace%20-%20Costs%27,viewMode:view)l)

**Comment by kvantricht** [comment]
Issue will be closed when https://github.com/WorldCereal/worldcereal-classification/pull/157 is merged. Contains https://github.com/WorldCereal/worldcereal-classification/commit/9b4333a3865ff4a5814c383a1673a9d89503c414 where minimal identifiers for job tracking were added.
