### ISSUE TITLE
Setup ground truth geoparquet generation pipeline using RDM API

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#125]
Create a function and an openEO job:

## The function:
Creates a GeoParquet of points samples and matching metadata:
* Either from a local dataset of polygons/points (WorldCereal Harmonized from @cbutsko)
* Either from a spatial/temporal extent used to query the RDM

The function implements a sampling of points from polygons with a strategy defined by the R&D team (start with centroid). And returns a GeoParquet of points with minimal metadata (GT code, SampleID, ...)

## OpenEO job:
Takes as input a GeoParquet of points to sample with additional metadata (GT, sampleID...)

From the collections of Sentinel1 and Sentinel2 patches, create a job that from input points samples:
* Sentinel 1 and Sentinel 2 data from the local stac collections
* METEO data from the pre-processed STAC collection available on CDSE bucket
* DEM data from global collection available on CDSE

Then performs processing such as monthly composites. Finally, concatenate GT and other metadata in a post-job action, returning a final GeoParquet with all the sample information alongside monthly-composited signal data and METEO/DEM.

**Comment by kvantricht** [comment]
> Additional note: the _GeoParquet of points with minimal metadata (GT code, SampleID, ...)_ should be uploaded to somewhere like Artifactory, so that it can be read with openeo.

based on what? Extractions that are finished?

**Comment by VincentVerelst** [comment]
After discussions with the openeo devs, we have decided to use the `load_url` process to load the reference data in openeo. For this two features need to be implemented on the VITO/CDSE backend:

- https://github.com/Open-EO/openeo-geopyspark-driver/issues/860
- https://github.com/Open-EO/openeo-geopyspark-driver/issues/859

**Comment by GriffinBabe** [comment]
Also depends on
- https://github.com/WorldCereal/worldcereal-classification/issues/151

I'm taking care of this this week

**Comment by HansVRP** [comment]
The decision has been made to develop this on the python client side. 
It is very specific to world cereal, so it will end up in the world cereal repo. 

Underlying technology to evaluate is duckdb/pandas.

requirement: location to store the geoparquet. (need to be accessible by terrascope back-end)
--> DIscuss with Peter/Jeroen

What defines success: Speed and efficiency

**Comment by jdries** [comment]
@VincentVerelst  can you close or provide status update?

**Comment by VincentVerelst** [comment]
@jdries , there's an open PR for this issue. Kristof will review after the WC demo.
