### ISSUE TITLE
Try using PCA on Presto embeddings

### ISSUE THREAD

**Issue by cbutsko** [WorldCereal/worldcereal-classification#14]

**Comment by cbutsko** [comment]
Detailed results [here](https://vitoresearch-my.sharepoint.com/:x:/g/personal/christina_butsko_vito_be/EYEvsyl8lllGpNiCc234XnYBwhoYQKJD2AvoUXViwFe4GA?e=pPbjwK). 

For each country with at least 1000 data points, a LOO test was performed, and PCA was fitted only on data used for training.

Overall results are not that consistent (even though the average gain is significantly bigger than average loss (**+0.058** vs **-0.039**). However, if we consider only those ref_id/country pairs that performed poorly on the finetuned Presto embeddings (F1 < 0.7), than we can observe quite consistent improvement!

**QUESTION:** Why is that and should we consider extracting PCs for regions with poor performance? In practical setup, this can be quite unobvious to implement. 

![image](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/c8716094-d7ea-4397-abf4-0dbd059b71f0)

**Comment by kvantricht** [comment]
Thanks! Make sure Gabi is aware of this, but I cannot tag him. Maybe permission related.

**Comment by kvantricht** [comment]
By the way, issue is not closed, right ;-)

**Comment by kvantricht** [comment]
Closed for now.
