### ISSUE TITLE
Add link on background info in RDM UI and organize background documentation (short explanation of harmonization and explaining attributes of downloaded data)

### ISSUE THREAD

**Issue by boog-wur** [WorldCereal/worldcereal-classification#159]
- Add link on background info in RDM UI (Santosh)
- Write small introduction on data harmonization and downloaded data (attributes) (Hendrik)
- Organize background docs (PDF with front page table on versioning - date, no, author) (Hendrik)

**Comment by santoshkaranam** [comment]
![Image](https://github.com/user-attachments/assets/d5dda774-cffe-46f1-9a9f-b410e0fee0ad)

I have added the links, please review the docs and let me know if needs update

**Comment by boog-wur** [comment]
I have prepared updated versions of these docs by adding WorldCereal layout and versioning table. In case of legend please use another version than the one used for upload as the first row is different (not an instruction but an explanation). 

Furthtermore, I suggest to not give a link to the "Dataset spatial accuracy calculation", this document is outdated and meant for the WorldCereal moderator only.

I have copied the documents to the teams, folder: https://vitoresearch.sharepoint.com/:f:/r/sites/21717-ccn-world-cereal/Shared%20Documents/System/RDM/Background_documents_for_RDM_UI?csf=1&web=1&e=ceKCNr 


So in summary

- WorldCereal crop type legend -> WorldCereal_crop_legend_ui_v2_20240709.pdf
- WorldCereal irrigation legend -> WorldCereal_irrigation_legend_ui_v2_20240709.pdf
- Observation date -> WorldCereal_DerivingValidityTime_v1_1.pdf
- Dataset confidence score calculation -> WorldCereal_ConfidenceScoreCalculations_v1_1.pdf
- Dataset spatial accuracy calculation -> no link

Finally, I wrote a background document ("WorldCereal_Background_Reference_Data_v1_0") introducing the harmonization and explaining the attributes. This needs review and then this document (as PDF) can also be added as a separate link.



Please note that the documents used in the **upload** also have new versions because of layout and versioning. See folder https://vitoresearch.sharepoint.com/:f:/r/sites/21717-ccn-world-cereal/Shared%20Documents/System/RDM/Protocol_adding_datasets?csf=1&web=1&e=ABa4Y7

In this folder updated documents are (version 1.1):
- WorldCereal_DerivingValidityTime_v1_1.pdf (observation date)
- WorldCereal_Reference_dataset_file_naming_convention_v1_1 (filename convention)

I also added the legend docs (the version with instruction) in this folder. These docs are not changed and are already used in the upload but these docs were not yet in this team folder:
- WorldCereal_crop_legend_v2_20240709
- WorldCereal_irrigation_legend_v2_20240709

**Comment by santoshkaranam** [comment]
@boog-wur I have taken docs from the above folder and updated the website deployment.

**Comment by jdegerickx** [comment]
Added quite a bit of information to the documentation portal.
We need to check whether the information there is complete and correct...
