### ISSUE TITLE
Sample free detection - Rapeseed - Using Google Earth Engine

### ISSUE THREAD

**Issue by shabarinath4** [WorldCereal/worldcereal-classification#165]
I get similar performance like Christina ~80 overall and ~25 in Spain. 
There are data points that fall outside or on the edge of the fields. Looks like multiple samples are drawn from each field in the ground truth. If we have access to these polygons we could draw samples towards the center which can improve the results. 

Next is to rerun the same model using timeseries data generated using the OpenEO pipeline

@cbutsko @kvantricht [1_2_SampleFree_method.pdf](https://github.com/user-attachments/files/17095036/1_2_SampleFree_method.pdf)

**Comment by kvantricht** [comment]
Same approach will be run on WorldCereal specific data.
