### ISSUE TITLE
Support multiple outputs for inference run

### ISSUE THREAD

**Issue by jdegerickx** [WorldCereal/worldcereal-classification#174]
For crop map, we want to have both the raw classification and post-processed classification downloaded as outputs when job finishes.

For crop type map, we even would like to have the crop mask (raw + post-processed?) + crop type map (raw + post-processed) generated in one go.

The solution implemented by Darius does not work currently, as execute_batch does not support download of multiple files.

This can be fixed by:
- ensuring each result is saved with a unique name (but there is currently a bug which causes the filename_prefix not being passed in save_result operation...) --> follow up with Jan
- do not provide an output path for execute_batch, but instead manually download all assets afterwards
- adjust InferenceResult class to support multiple outputs

**Comment by kvantricht** [comment]
@jdegerickx this one can be closed?

**Comment by jdegerickx** [comment]
yes
