### ISSUE TITLE
Change STAC hrefs from `/vitodata/` to `/data/`

### ISSUE THREAD

**Issue by VincentVerelst** [WorldCereal/worldcereal-classification#210]
The share on which the extractions are saved (`netapp03.vgt.vito.be:/worldcereal_data`) is currently mounted on all uservms on `/vitodata/worldcereal_data`, but will be moved to `/data/worldcereal_data`. 

Therefore the hrefs of all STAC collections also need to be adjusted.

**Comment by cbutsko** [comment]
@VincentVerelst my S1 extractions finished, so you can go ahead and update S1 STAC.
