### ISSUE TITLE
setup OpenEO service account / client credentials

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#24]
- For both CDSE and Terrascope
- Increased batch job limit (on CDSE)

**Comment by soxofaan** [comment]
just created service account `openeo-worldcereal-service-account` on VITO terrascope (see openeo-deploy repo for details)

**Comment by soxofaan** [comment]
Checking with @JanssenBrm  to also set one up on CDSE (has to go through cloudferro ticket)

**Comment by soxofaan** [comment]
requested creation of client under CF Jira ticket  CDSE-776 . Not sure how long that will take

**Comment by soxofaan** [comment]
I got the credentials from cloudferro.
The one against production keycloak works
The one against staging keycloak has still a problem, waiting for  CDSE-776 follow up

credentials are in Vito vault (.../cdse-service-accounts/openeo-worldcereal-service-account and .../cdse-staging-service-accounts/openeo-worldcereal-service-account)

**Comment by soxofaan** [comment]
minor update:
account on staging CDSE keycloak has still problem when authenticating :

> 404 'Not Found' '{"error":"Your account is not configured correctly - You don\'t have any organization assigned to You."}'

still waiting for cloudferror to resolve that

Production acounts are in place and should work however

**Comment by kvantricht** [comment]
@soxofaan status update?

**Comment by soxofaan** [comment]
CDSE-776 is still "in progress" on CloudFerro's side. We escalated that somewhere last week, but still little movement from their side

But to be clear and summarize: 

What is already in place:
- client cred access to VITO/Terrascope backend `openeo.vito.be` with client id `openeo-worldcereal-service-account`
- client cred access to CDSE backend `openeo.dataspace.copernicus.eu` with client id `openeo-worldcereal-service-account`

Client secrets for both are available in Terrscope Vault (e.g. for programmatic extraction)

The only thing that is actually still hanging is the client credentials access to CDSE **staging** (openeo-staging.dataspace.copernicus.eu), which is not really that important I guess. We might even consider ignoring that and just close this #24

**Comment by soxofaan** [comment]
Just got notification that CDSE-776 is resolved 

this does not seem to happen anymore:
> account on staging CDSE keycloak has still problem when authenticating :
>>    404 'Not Found' '{"error":"Your account is not configured correctly - You don't have any organization assigned to You."}'


So we can close this one

In summary, what is now in place:

- client cred access to VITO/Terrascope backend openeo.vito.be with client id openeo-worldcereal-service-account
- client cred access to CDSE backend openeo.dataspace.copernicus.eu with client id openeo-worldcereal-service-account
- client cred access to CDSE staging backend openeo-staging.dataspace.copernicus.eu with client id openeo-worldcereal-service-account

Client secrets for both are available in Terrscope Vault (e.g. for programmatic extraction)
