### ISSUE TITLE
Hierarchical Classification: LCPN

### ISSUE THREAD

**Issue by cbutsko** [WorldCereal/worldcereal-classification#25]
Check whether Local Classifier Per Node strategy in the hierarchical classification allows to:
1. Have access to local classifiers
2. Once new class appears, train only one local classifier for this particular new label. It should be able to utilize all the information from upper-level classifiers that have already be trained. **Question:** how this will affect downstream or even parallel classifiers? Should they also be retrained if new label appears?

**Comment by kvantricht** [comment]
This issue is currently in the backlog. Is it related to other issues, do we have to move it into current or next iteration?
