### ISSUE TITLE
Presto performance benchmarking

### ISSUE THREAD

**Issue by jdegerickx** [WorldCereal/worldcereal-classification#3]

**Comment by cbutsko** [comment]
Detailed results [here](https://vitoresearch-my.sharepoint.com/:x:/g/personal/christina_butsko_vito_be/EYEvsyl8lllGpNiCc234XnYBwhoYQKJD2AvoUXViwFe4GA?e=IirFA7)

Finetuned Presto embeddings demonstrate overwhelming excellence over the combination of all available raw features (optical+sar+temperature+precipitation+DEM+lat+lon).

![image](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/e994e010-0b61-4266-a669-f11cfae98730)
