### ISSUE TITLE
Define locations for additional cropland/croptype patches

### ISSUE THREAD

**Issue by cbutsko** [WorldCereal/worldcereal-classification#30]
This issue is about defining the location of the patches themselves. Extracting data happens in another issue.

**Comment by kvantricht** [comment]
@cbutsko can you give an update? Is this ongoing/needed?

**Comment by kvantricht** [comment]
Need to query RDM for available crop type datasets and define patch locations based on those.

**Comment by cbutsko** [comment]
29 new patches are defined here: `/vitodata/worldcereal/presto/testpatches/inference_croptype/croptype_inference_patches.gpkg`

Each patch has the following attributes:

- _sample_id_ (string): a short description of patch, now roughly constructed as _{country}___{crop}_
- _GT_available_ (bool): indicates whether RDM contains reference data for the patch
- _valid_time_ (date): if patch has GT available, then valid_date is taken from available data; if not - an educated guess based on targeted search is made; for those patches that don't have GT data available, 2021 is always chosen (for no particular reason)
- _extract_ (int): ancillary attribute indicating whether the patch should be extracted (>0) or not (==0)  

They are created based on combination of aggregated SPAM maps and existing RDM statistics (described in more detailes in [issue 56](https://github.com/orgs/WorldCereal/projects/3/views/9?pane=issue&itemId=69801122))
**15** of these patches contain at least some corresponding GT data in the RDM (sometimes as few as just 4-5 points). Other 14 patches are selected based on expected density of a crop in aggregated SPAM map. 

Focus is made on crops that are the first priority for WorldCereal: maize, soybean, rapeseed, sunflower, millet, sorghum, wheat, barley.
