### ISSUE TITLE
Do extractions for newly defined cropland/croptype inference patches

### ISSUE THREAD

**Issue by cbutsko** [WorldCereal/worldcereal-classification#31]
Once patches are defined (#30) we can extract the actual data; don't forget to re-extract with the new pipeline the existing patches for a sanity check. This can be done using the functionality here: https://github.com/WorldCereal/worldcereal-classification/blob/demo/src/worldcereal/job.py#L286

```
spatial_extent = BoundingBoxExtent(minx, miny, maxx, maxy, epsg)
temporal_extent = TemporalContext(start_date, end_date)

backend_context = BackendContext(Backend.FED)

collect_inputs(
    spatial_extent: BoundingBoxExtent,
    temporal_extent: TemporalContext,
    backend_context: BackendContext,
    output_path: Union[Path, str],
)
```

**Comment by kvantricht** [comment]
@cbutsko how should we tackle this? What I did for crop/no-crop was checking the Phase I calendars to define a extraction window of one year. Maybe here we should have a fixed wide window? Season should have ended in 2021, but can start already in 2020. Maybe `2020/06/01 - 2021/12/31` as extraction window for all patches allows us to cover all possible scenarios? Or start even earlier? We need to check though how to deal with this in presto (or how to decide which 12 months of the longer time series to feed to Presto). Thoughts?

**Comment by cbutsko** [comment]
I agree that for croptype taking a fixed wide window makes sense. Maybe we can then run the _find_peaks_ method to choose the best 12-month window that aligns with found vegetation peaks and puts them in the center? this way, we might end up with more then 1 time-series per patch (in case multiple peaks are detected), but compatibility with presto should be solved then

**Comment by kvantricht** [comment]
indeed, to be discussed. We should probably find the peak closest to the season defined by the crop calendars (but also allow maybe run separately from them if needed). Anyway, so for now the 2020/06/01 - 2021/12/31 range it is.

**Comment by kvantricht** [comment]
First set of new patches has been downloaded to: `/vitodata/worldcereal/presto/testpatches/inference_croptype`
These were generated using the following command:

```
python extract.py WORLDCEREAL /vitodata/worldcereal/presto/testpatches/inference_croptype/ /vitodata/worldcereal/presto/testpatches/inference_croptype/croptype_inference_patches.gpkg --memory 2G --python_memory 3000m --extract_value 1 --max_executors 11 --parallel_jobs 2 --max_locations 500 --disable_stac
```
