### ISSUE TITLE
Collect new sampling procedure statistics

### ISSUE THREAD

**Issue by cbutsko** [WorldCereal/worldcereal-classification#33]
New sampling procedure using H3 hierarchical grid has been implemented [here](https://github.com/WorldCereal/worldcereal-referencedata/blob/main/harmonization/harmonize_phase_I.py)
Sampling was performed at a dataset level and per crop group. Crop grouping was done on the basis of new WorldCereal legend and can be found [here](https://github.com/WorldCereal/worldcereal-referencedata/blob/main/harmonization/resources/ewoc_legend_sampling_edition.csv)

The following groups were used for sampling:

**Not Cropland Classes:**
`
not_crop_classes = ['pasture_meadows',
    'trees_unspecified',
    'non_cropland_incl_perennial',
    'built_up',
    'shrubland',
    'open_water',
    'other_permanent_crops',
    'fruit_nuts',
    'herbaceous_vegetation',
    'permanent_crops',
    'non_cropland_excl_perennial',
    'greenhouse_foil_film_indoor',
    'bare_sparsely_vegetated',
'kitchen_allotment_gardens',
'not_cultivated_fallow']
`

**Cropland Classes:**
`
crop_classes = ['barley', 'cereals',
       'dry_pulses_legumes', 'fibre_crops', 'flower_crops',
       'grass_fodder_crops', 'herb_spice_medicinal_crops',
       'maize', 'millet_sorghum',
       'mixed_arable_crops', 'mushrooms_truffles',
       'oats', 'oilseed_crops', 'other_cereals',
       'other_crop', 'other_oilseeds', 'pseudocereal', 'rapeseed_rape',
       'rice', 'root_tuber_crops', 'rye', 'soy_soybeans', 'sunflower',
       'temporary_crops', 'vegetables_fruits', 'wheat']
`

This task is created to investigate the following:

- [x] compare counts and spatial distribution of the new sampling procedure and the previous samples extracted during WorldCereal Phase I
- [x] visualize distribution of samples that will be used in Phase II

**Comment by cbutsko** [comment]
Comparison of samples for not cropland classes:

![samples_distribution_not_cropland_phase1](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/7702b748-86d2-4095-8194-2bbbb45be128)
![samples_distribution_not_cropland_phase2_extract0](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/bfda2e76-832a-401a-bbfd-0e4b785db81e)

**Comment by cbutsko** [comment]
Comparison of samples for cropland classes:

![samples_distribution_cropland_phase1](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/5fedff16-0d08-4f85-923d-c2ccf1d4cb0b)
![samples_distribution_cropland_phase2_extract0](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/f3942f7e-7994-4750-9ed2-081a587fb748)

**Comment by kvantricht** [comment]
This is some kind of density plot right? It's a bit unclear to me what is under "cropland classes", that's all cropland datapoints, regarding if we have crop type information for them or not? Although there's a better spread now, there seems to be larger "blind spots" compared to earlier plots we had, but that's likely because low density samples, such as points from EWOCO dataset do not pop up here. It's probably a detail, but to identify true large blind spots from the map, we should maybe be able to also spot the low-density regions.

**Comment by cbutsko** [comment]
very good points, thanks! Indeed, no EWOCO datasets are present here (as they are still for the metadata to be ingested into the RDM). In order to align results, I compared results only for those datasets that have been processed by the new procedure, so this can be updated as other datasets are processed. The primary aim for me now was to see how the density of samples changed with the sampling procedure. Once 

As for "cropland classes", I updated the issue description to show which classes I considered to be cropland. This is an arbitrary division, just for visualization purposes. 

I'll update the plots a little to better depict blind spots and low-density regions.

**Comment by cbutsko** [comment]
Updated plot with legend and divided by confidence for better visibility.  Some territories/countries (Greenland, Iceland, Norwegian arctic territories, France territories near South America, Russia) is excluded for visualization purposes.
**Not Cropland classes:**

**Africa**
![samples_distribution_not_cropland_phase1_Africa](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/e0b6285a-61d2-4f3a-8b47-3d9d1ee2bda9)
![samples_distribution_not_cropland_phase2_extract0_Africa](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/8b71b5c0-d865-49e7-a999-1c8371248a95)

**Asia**
![samples_distribution_not_cropland_phase1_Asia](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/6800af63-5f7e-4a0f-a4d5-5c1f0ab3cabd)
![samples_distribution_not_cropland_phase2_extract0_Asia](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/746c6459-d84c-4c85-b7f6-69be61a149b1)

**Europe**
![samples_distribution_not_cropland_phase1_Europe](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/f539aef7-f617-4fcb-a3f1-164541544d5a)
![samples_distribution_not_cropland_phase2_extract0_Europe](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/821d1feb-b940-43dc-a0d1-41bba3b4c80b)

**North America**
![samples_distribution_not_cropland_phase1_North America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/460bb2a7-9bd9-413e-a8e9-5660aa9f1afc)
![samples_distribution_not_cropland_phase2_extract0_North America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/27a03e88-9be0-44e2-81a9-17359eeee402)

**South America**
![samples_distribution_not_cropland_phase1_South America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/c683cf00-e2a2-4120-acdc-0f9cd65ea44b)
![samples_distribution_not_cropland_phase2_extract0_South America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/ac3a1e9d-1e19-4421-991d-96014d2c0ac9)

**Comment by cbutsko** [comment]
Updated plots with legend and divided by continents for better visibility.  Some territories/countries (Greenland, Iceland, Norwegian arctic territories, France territories near South America, Russia) is excluded for visualization purposes.
**Cropland classes:**

**Africa**
![samples_distribution_cropland_phase1_Africa](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/d15ac0f5-8d4e-4d0e-a208-ef3e59917293)
![samples_distribution_cropland_phase2_extract0_Africa](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/c461793f-4db4-41c6-9240-fce9bbbe4e0b)

**Asia**
![samples_distribution_cropland_phase1_Asia](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/42837863-1919-4029-8705-cba4cd5e660c)
![samples_distribution_cropland_phase2_extract0_Asia](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/ae9c358a-fd86-4cd9-8fb8-49f3db940256)

**Europe**
![samples_distribution_cropland_phase1_Europe](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/e61debcf-5f22-4c15-b3b5-68533a064eec)
![samples_distribution_cropland_phase2_extract0_Europe](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/29fbd8df-d7c3-4132-8246-de1770d189d5)

**North America**
![samples_distribution_cropland_phase1_North America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/03a44f30-f062-4c55-a302-4bd205ca42bf)
![samples_distribution_cropland_phase2_extract0_North America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/97121234-8fe8-4d00-a534-59617f958085)

**South America**
![samples_distribution_cropland_phase1_South America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/a7babca3-3153-41cf-9427-af45a2f5bf13)
![samples_distribution_cropland_phase2_extract0_South America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/19679a96-fa9f-4e9e-a168-670df82eaa24)

**Comment by cbutsko** [comment]
Here's more visually telling comparison by continents.

**CONCLUSION:** new sampling procedure does provide much better spatial diversity and allows to fill in the gaps present in the Phase I data, while still keeping the number of samples feasible. This is especially visible on the example of the North America.

While EWOCO and France datasets haven't been processed yet, the spatial distribution of cropland is significantly expanded compared to Phase I dataset:
![djf_sampling_comparison_North America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/06296e4e-cc0a-4a5e-b4f6-6c42dc5acb10)
![djf_sampling_comparison_South America](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/b6256302-bf25-42b4-85b7-d9dc473488b6)
![djf_sampling_comparison_Europe](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/3c78c742-5fa6-41f1-9846-5de8185484f6)
![djf_sampling_comparison_Asia](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/ca1aae05-c2cc-4dfa-9284-5cb2644289aa)
![djf_sampling_comparison_Africa](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/8c0eb146-5469-42e3-b8d0-4aa1e1e850ce)
