### ISSUE TITLE
Implement WorldCereal inference pipeline using GFMAP

### ISSUE THREAD

**Issue by GriffinBabe** [WorldCereal/worldcereal-classification#38]
As discussed with @GriffinBabe, I worked on a minimal example showing the entire flow required to create a crop/no-crop map for WorldCereal in OpenEO.
 
The notebook is here: https://github.com/WorldCereal/wc-classification/blob/openeo/notebooks/OPENEO/inference_example_openeo.ipynb
 
Actual inference code is here: https://github.com/WorldCereal/wc-classification/blob/openeo/src/worldcereal/openeo/inference.py
 
It's so far not yet done with GFMAP. Example starts from pregenerated result from the `worldcereal_preprocessed_inputs` block, which in GFMAP terminology contains the data fetching and preprocessing steps.
That NetCDF is loaded and a UDF is applied to it locally. That UDF contains both feature extraction (using presto encoder) and model inference (using catboost).
 
Only works locally for numerous reasons:
No env compiled yet that contains the required libraries
Access needed to EPSG (hardcoded for the moment) to get the coordinates required as input for Presto
On CDSE wouldn't work yet anyway because Meteo collection loader is required
Probably this effort should only be done when we know how to do it in GFMAP directly instead of first as a standalone and then refactoring it.

**Comment by HansVRP** [comment]
Here the repo where I have been working on the mvp example:
 
https://github.com/WorldCereal/worldcereal-classification/tree/hv_mvp_inferenceUDF/minimal_wc_presto

**Comment by HansVRP** [comment]
TODO; check how the developed architecture would work with the delivered UDF for inference
