### ISSUE TITLE
LSP-based crop calendars

### ISSUE THREAD

**Issue by MolettoLobos** [WorldCereal/worldcereal-classification#39]

**Comment by MolettoLobos** [comment]
First version operative version LSP phenology metrics using MYDCMG at 0.05° resolution using [HANTS ](https://www.sciencedirect.com/science/article/pii/S0034425715001145)method 

![Image](https://github.com/WorldCereal/worldcereal-classification/assets/50592195/a845f227-3571-4e9b-bb0b-dc1123a66b59)
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/50592195/52b2f719-ac29-44d8-b9b7-d0c13a154a78)
Validation is still pending

**Comment by kvantricht** [comment]
@MolettoLobos can you give an update on the progress for this issue?

**Comment by MolettoLobos** [comment]
@kvantricht ! Still on doing (working on validation)

**Comment by MolettoLobos** [comment]
The percentage of crop cover at 0.05º deg. In the area under  red polygon (AEZ ) was used to detect possible dormancy area using two peaks detector. The rest is used just with the one peak detection  

![percentage_study_area](https://github.com/user-attachments/assets/5675d4ea-991b-4ec7-b482-3e0e2b714a81)

the example of analysis 
![image](https://github.com/user-attachments/assets/7e8659c9-4a78-4756-8b6a-bb835c2e817b)

The resulting are the following datasets

![image](https://github.com/user-attachments/assets/7294f7ab-7082-44e9-8ab4-285622ff6af9)

where are transformed to 0.5º deg resolution for re-train the model at global scale providint the second iteration

![image](https://github.com/user-attachments/assets/3e8b7a9f-231d-405b-910b-7c9ef716e0f9)

**Comment by MolettoLobos** [comment]
![image](https://github.com/user-attachments/assets/ccc54033-3ada-4394-a053-10c3cf8e1a0d)
grouped classes into two seasons
