### ISSUE TITLE
Set up experiments to check SatCLIP Encoding usefulness

### ISSUE THREAD

**Issue by jdegerickx** [WorldCereal/worldcereal-classification#4]
[First results](https://vitoresearch-my.sharepoint.com/:x:/g/personal/christina_butsko_vito_be/EYEvsyl8lllGpNiCc234XnYBwhoYQKJD2AvoUXViwFe4GA?e=SxVeRP) indicate that SatCLIP gives quite a boost to raw features.

Once train/val files are updated, needs to be checked if the same effect happens with presto + satclip features. Depends on [issue 24](https://github.com/WorldCereal/presto-worldcereal/issues/24)

**Comment by cbutsko** [comment]
For finetuned Presto features, performance boost is not that convincing and wide-spread.
![image](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/18dd6211-a996-4090-9605-5d25a474417b)

**Next steps:**

- [ ] try other SatCLIP models
    - [ ] resnet18_l10
    - [ ] resnet19_l40
    - [ ] resnet50_l10
    - [ ] resnet50_l40
    - [ ] vit16_l10
    - [ ] vit16_l40

- [ ] check if there's any pattern to when SatCLIP features give boost; a quick look suggests that ref_ids that get the most boost (top10) have average F1 without SatCLIP of 0.79, while those ref_ids that suffer the most (bottom10) have average F1 without SatCLIP of 0.71. Completely opposite picture is seen when looking at boost that Presto gives compared to raw features: top10 places that have the most boost from Presto have average raw features F1 of 0.31, while bottom10 places have F1 of 0.87. Can it be that SatCLIP is more effective in places where models already do quite well, but confuses the model even more in places where quite some confusion was happening even without SatCLIP?

**Comment by cbutsko** [comment]
Unfortunately, no prominent effect is observed when any features from SatCLIP models are added to finetuned Presto embeddings. The chart shows sorted F1 scores of multiple models, with solid line being the F1 score of finetuned Presto embeddings. It is seen that all SatCLIP variations oscillate around the baseline line, with more complex models yielding some unexpected peaks in both directions:
![satclip_influence_on_performance](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/fbd64bc0-78ca-4bfe-bcb8-7059e90bb615)

Below are spatial patches predicted with the lightest SatCLIP model (along other models for comparison) - resnet18_l10. Again, no obvious benefit is seen from adding SatCLIP 🤷‍♀️

![argentina wetlandcommission](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/f2be2f02-6067-4c6b-a018-2e968236561b)
![australia omission](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/926ba2e9-65d7-43a7-ae72-c47cb2ebec91)
![belgium good](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/53615207-bd53-428c-8fe8-efdd9d51891b)
![drc omission](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/7c5189c7-77d6-4241-804f-cda561c3696e)
![ethiopia commission](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/c38c548a-0f78-46f9-8962-51aaf01c54e6)
![madagascar confusion](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/bfeeb61b-4272-442c-8acf-f2ef6d2b1324)
![mexico confusion](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/ac717335-1401-4487-917e-d140846473a9)
![russia omission](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/a8cabedd-58ca-47d4-b5b9-e4ae507836eb)
![sudan omission](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/d9c8e3d1-dfe1-47e4-85ce-bf00763af6e6)
![togo omission](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/b8a36c73-1dae-450f-ab2f-99c8c6ff6717)
![uganda artefact](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/ac0cfeb1-bb99-4b4e-b510-03a547252eb9)
![uzbekistan noise](https://github.com/WorldCereal/worldcereal-classification/assets/10546825/33a08130-3202-4c32-addd-1d02bb433518)

**Comment by kvantricht** [comment]
For the moment we won't pursue this further.
