### ISSUE TITLE
integration of maize1, maize2 and wheat into two seasons

### ISSUE THREAD

**Issue by cyrankate** [WorldCereal/worldcereal-classification#40]
Quality check of all points and aggregation into 2 seasons according to USDA calendars and GEOGLAM crop monitor

**Comment by cyrankate** [comment]
Some examples also highlighted in the DJF.
1. Kenya
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/156313575/bdcf4e93-0cc0-432f-9430-e934e7c70f5e)
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/156313575/ab3b2045-d0bd-4e8d-8d10-5b518d7aba83)
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/156313575/0574ed5d-99b9-49da-8c32-15a112444b02)

2. Mexico
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/156313575/77ada2a5-cc83-4c0c-b045-a470faaa8303)
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/156313575/1840a1a6-715c-4e80-9dfa-f629dfc8d70e)
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/156313575/abcc7868-991e-47e3-b986-8a8344ac701b)

3. Argentina
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/156313575/9649971d-187f-47c6-aaa9-c33fb1e4ea90)
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/156313575/20867fe5-557e-431e-b415-f996abbe8ffc)
![Image](https://github.com/WorldCereal/worldcereal-classification/assets/156313575/ea278b31-27be-49e6-aa2c-e8631b6a5e4f)

**Comment by angui3** [comment]
This task is already completed.
