### ISSUE TITLE
openEO based feature computation workflow

### ISSUE THREAD

**Issue by jdegerickx** [WorldCereal/worldcereal-classification#5]
~~Prepare the feature computation workflow as described in the internal loop page~~

This more general description was moved to issue #6

Implement the feature extractor UDF for patch, point and polygon workflows and implement tests

- [x] Patch/polygon feature extractor
- [ ] Point feature extractor
- [x] Implement tests

**Comment by GriffinBabe** [comment]
Point feature extractor could be implemented later as we don't need it urgently for the extractions
