### ISSUE TITLE
Define AOI for sample-free alternative classification approaches

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#51]

**Comment by shabarinath4** [comment]
**Crops to Experiment**

Wheat
Maize
Rapeseed
Rice
Sorghum
Soyabean
Sunflower

**AOI**

**_Group 1_**

1. Ukraine - Ternopilska, Vinnystka
2. France - TBD
3. Brazil - Goias, Mato Grosso, Mato Grosso du Sul, Goias

**_Group 2_**

1. Malawi - Lilongwe
2. Ethiopia - TBD
3. India - Punjab, Madhya Pradesh

**Comment by shabarinath4** [comment]
Next:

1. Get train, test and inference data for the above regions (S1,S2,Weather,L8)
2. Generate simulation data in Ethiopia
3. Run experiments

**Comment by kvantricht** [comment]
Getting preprocessed inputs using openEO should now be relatively straightforward with: https://github.com/WorldCereal/worldcereal-classification/blob/main/scripts/extractions/patch_extractions/extract.py
