### ISSUE TITLE
udf memory profiling

### ISSUE THREAD

**Issue by jdries** [WorldCereal/worldcereal-classification#57]
Current setting of memory overhead is 12GB, which is a bit much for operational production.

Looking up memory consumption shows very clear peaks when presto is invoked. The actual max usage is even higher, because prometheus only records memory at specific instants.

![Image](https://github.com/WorldCereal/worldcereal-classification/assets/5937096/72ac7cf1-c9b0-482e-90c2-fab68e029f5e)

**Comment by GriffinBabe** [comment]
@jdries  I'm creating a branch for this issue and provide you with a script to locally test presto

**Comment by kvantricht** [comment]
meanwhile already also made a PR to expose `batch_size` parameter for presto inference https://github.com/WorldCereal/worldcereal-classification/pull/59
