### ISSUE TITLE
Investigate AgERA5 access from CDSE

### ISSUE THREAD

**Issue by jdegerickx** [WorldCereal/worldcereal-classification#7]

**Comment by soxofaan** [comment]
@jdegerickx  are there more details about this task, or who should I talk to?

**Comment by jdegerickx** [comment]
@kvantricht can further explain.
But basically we need access to AgERA5 data (now hosted on terrascope --> see /MTDA/AgERA5) for training and applying our crop type models and this data is currently not available on CDSE.

**Comment by kvantricht** [comment]
> @jdegerickx are there more details about this task, or who should I talk to?

@jdries is also aware of this request. The main question is how we can access meteo data from CDSE. Feel free to assign to whomever could take up the task.

For training extractions we can for now use Terrascope backend to generate meteo NetCDF, but by the time we go towards inference, meteo should be directly accessible from CDSE (and that will be soon).

**Comment by jdries** [comment]
we can build a stac catalog, as we now anyway have a service for openEO
For hosting of the files, either can try to do it from terrascope, or simply upload into CF object storage.

**Comment by soxofaan** [comment]
As discussed in sprint meeting, I think this ticket can be closed as we decided to work through the Terrascope backend + load_stac
