### ISSUE TITLE
Create openeo UDP for generating worldcereal products

### ISSUE THREAD

**Issue by jdegerickx** [WorldCereal/worldcereal-classification#73]
We now have a preliminary version of a workflow generating a default worldcereal product for a custom AOI and year.
For now, only crop/no-crop classification is supported, will be extended with crop type as well...
Also, currently the generate_map function does not support supplying a custom model URL.

Demo can be found here --> https://github.com/WorldCereal/worldcereal-classification/blob/demo/notebooks/system_v1_inference.ipynb

Perhaps we can already convert this into a preliminary UDP for further testing (also in the Maps4GPP project)?

@jdries, feel free to assign this issue to someone else of course ;)

**Comment by jdries** [comment]
The UDP was created and added to APEx, use of it is documented here:
https://worldcereal.github.io/worldcereal-documentation/usage/processing_api.html

**Comment by jdries** [comment]
@soxofaan  for next steps, write script that parameterizes the datacube that is contstructed here:
https://github.com/WorldCereal/worldcereal-classification/blob/main/src/worldcereal/job.py#L162

important parameters are:

* spatial extent
* temporal extent (with default settings for 2021)

**Comment by jdegerickx** [comment]
Update: the generate_map function has been extended and can also support crop type inference runs, even with custom models --> https://github.com/WorldCereal/worldcereal-classification/blob/main/src/worldcereal/job.py#L177

So we would need a UDP which can run this function based on:
- spatial extent
- temporal extent
- product type
- (optional) product parameters
I would say that for output format, backend and tile size we can just use the defaults as specified in the generate_map function arguments.

See also here an example of how this function is used in a demo notebook -->
https://github.com/WorldCereal/worldcereal-classification/blob/extra-demos/notebooks/system_v1_inference.ipynb
