### ISSUE TITLE
Improve S1 extractions

### ISSUE THREAD

**Issue by GriffinBabe** [WorldCereal/worldcereal-classification#79]
Improve S1 extractions:

- [x] Assess the quality of the results
- [ ] Optimize resource consumption
- [x] Create a job for ascending and descending products

**Comment by kvantricht** [comment]
Currently issue with nodata row/column. To be fixed on OpenEO side. To followed up by either @soxofaan or @jdries .

**Comment by soxofaan** [comment]
> Currently issue with nodata row/column. To be fixed on OpenEO side. To followed up by either @soxofaan or @jdries .

can you give some more info or a reference what this is about?

**Comment by soxofaan** [comment]
or is it this one?
- https://github.com/Open-EO/openeo-geopyspark-driver/issues/821

**Comment by kvantricht** [comment]
Hans answered in openeo-users channel that he filed a bug, but didn't make a reference to which one and he's currently out of office. So I can't say for sure.

**Comment by soxofaan** [comment]
@HansVRP  can you shine a light on this?

**Comment by HansVRP** [comment]
Apologies, the follow-up was lingering on my todo list. It is indeed the one you mentioned @soxofaan. I only made a quick draft, based on the post in the team's channel.

**Comment by soxofaan** [comment]
looping in @JeroenVerstraelen  as this probably involves some massaging of the sprint planning
