### ISSUE TITLE
add spatial cleaning to inference workflow as postprocessing step

### ISSUE THREAD

**Issue by jdegerickx** [WorldCereal/worldcereal-classification#98]
in the demo notebook I implemented a simple majority vote based on what has been done in HRL, but this still requires further testing and tuning.
In HRL in the end we used a more advanced technique based on gdal sieve --> investigate whether this is possible and desirable here...

**Comment by jdegerickx** [comment]
@kvantricht, not sure who to assign this to?

**Comment by kvantricht** [comment]
Options:
- implement on `worldcereal-classification` side (short-term solution), by integrating postprocessing into the classification UDF (saving postprocessed label, max probability and the original class probabilities)
- implement a `postprocessor` method/UDF within `openeo-gfmap` which is configurable by other libraries making use of this method.

@kvantricht to setup meeting with @HansVRP and @GriffinBabe to discuss option 2
@GriffinBabe to link here to some existing code from HRL as a reference

One workflow that needs to be part of this is based on `gdal_sieve`. Question: is such operation available within OpenEO? To be checked with @jdries

**Comment by GriffinBabe** [comment]
The smooth and reclassify operation, which I propose to start with is implemented here:
https://git.vito.be/projects/APPL/repos/cropclass/browse/src/cropclass/postprocessing/operations.py#93µ

**Comment by kvantricht** [comment]
- add `save_results()` after classification to be able to save raw classification results before postprocessin

**Comment by kvantricht** [comment]
Closed by https://github.com/WorldCereal/worldcereal-classification/pull/157
