### ISSUE TITLE
Solve memory issues for larger inference jobs

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/worldcereal-classification#99]
Currently any job beyond 5km X 5km fails with a confusing memory issue. This needs to be investigated and fixed before we can send this system for review to ESA.

**Comment by kvantricht** [comment]
Currently updating the `executor-memory` and `executor-memoryOverhead` greatly helped.

```
job_options={
            "driver-memory": "4g",
            "executor-memory": "3g",
            "executor-memoryOverhead": "5g",
            "udf-dependency-archives": [f"{ONNX_DEPS_URL}#onnx_deps"],
}
```

**Comment by jdries** [comment]
Further investigation revealed this issue:
https://github.com/Open-EO/openeo-gfmap/issues/142

I also added a new config to better constrain python memory use: 
https://github.com/eu-cdse/openeo-cdse-infra/issues/44
And then made decommission less aggressive:
https://github.com/eu-cdse/openeo-cdse-infra/issues/197

With these things combined, I could run a job with total executor memory of 4GB.
